### ISSUE TITLE
idea for string encryption

### ISSUE THREAD

**Issue by Iloliks229** [ColonialBuilders/ColonialObfuscator#3]
to decrypt string keys, you can use several keys at once, for example, they must consist of each letter of the string that will be encrypted, this string can also be divided into several parts that will strengthen the protection of the application, they must be converted to the Int format and the int must also be divided into several parts `255, 255, 255, 255, 255` I think it's a good idea, implementation is quite possible as in some obfuscators

**Comment by ColonialBuilders** [comment]
i added more keys to String encryption
